---
- name: "Installing the vnc package"
  yum: pkg={{ item }} state=installed
  with_items:
  - tigervnc
  - tigervnc-server

- name: "Copying the vnc configuration file"
  copy: 
    src: vncserver@:1.service
    dest: /etc/systemd/system/vncserver@:1.service
    owner: root
    group: root
    mode: 0644

- name: "Create the remote /root/.vnc directory"
  file:
    path: /root/.vnc
    mode: 0755
    state: directory

- name: "Generate vnc password for root user remotely"
  shell: |
      echo Embe1mpls | vncpasswd -f > /root/.vnc/passwd

- name: "Change the permission to 600 for /root/.vnc/passwd file"
  file:
    path: /root/.vnc/passwd
    mode: 0600

- name: "Start & enable the vncserver"
  systemd:
    state: started
    daemon_reload: yes
    name: vncserver@:1
    enabled: True
