# -*- mode: ruby -*-
# vi: set ft=ruby :
vagrant_root = File.dirname(__FILE__)
contrail_version = 'master-latest'
interface = 'eth1'
gateway_ip = '10.155.95.254'
ip_prefix = '10.155.75.18'
netmask = '255.255.224.0'
dns1 = '172.21.200.60'
dns2 = '8.8.8.8'
domain = 'englab.juniper.net jnpr.net juniper.net'
ntp_server = 'ntp.juniper.net'

Vagrant.configure("2") do |config|
  config.vm.box = 'qarham/CentOS7.5-350GB'
  config.vbguest.auto_update = false
  config.vm.synced_folder '.', '/vagrant', disabled: true

  (1..3).each do |id|
    node_name = ( "ha-node" + id.to_s ).to_sym
    config.vm.define node_name do |node|
      node.vm.hostname = "ha-node#{id}"
      node.vm.provider "virtualbox" do |v|
        v.memory = 48000
        v.cpus = 8
        end
      node.vm.network "public_network", auto_config: false, bridge: 'eno1'
      node.vm.provision :ansible do |ansible|
        ansible.playbook = "#{vagrant_root}/ansible/network.yml"
        ansible.extra_vars = {
          vm_interface: "#{interface}",
          vm_gateway_ip: "#{gateway_ip}",
          vm_ip: "#{ip_prefix}#{id}",
          vm_netmask: "#{netmask}",
          vm_dns1: "#{dns1}",
          vm_dns2: "#{dns2}",
          vm_domain: "#{domain}",
          ntp_server: "#{ntp_server}",
          contrail_version: "#{contrail_version}",
          vagrant_root: vagrant_root
        }
      end
      node.vm.provision :ansible do |ansible|
        ansible.playbook = "#{vagrant_root}/ansible/setup.yml"
      end
      node.vm.provision "file", source: "#{vagrant_root}/ansible/scripts/all.sh", destination: "/tmp/all.sh"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "all" => ["ha-node1"]
    }
    ansible.playbook = "#{vagrant_root}/ansible/ha.yml"
    ansible.extra_vars = {
      primary: {"host": "ha-node1", "ip": "10.155.75.181"},
      secondaries: [{"host": "ha-node2", "ip": "10.155.75.182"},
                    {"host": "ha-node3", "ip": "10.155.75.183"}],
      ntp_server: "ntp.juniper.net",
      contrail_version: contrail_version,
      vagrant_root: vagrant_root
    }
  end

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "all" => ["ha-node1"]
    }
    ansible.playbook = "#{vagrant_root}/ansible/command.yml"
    ansible.extra_vars = {
      vm_ip: "10.0.2.15",
      ntp_server: "ntp.juniper.net",
      contrail_version: contrail_version,
      vagrant_root: vagrant_root
    }
  end

  config.vm.define 'cc' do |cc|
    cc.vm.hostname = 'cc'
    cc.vm.network "forwarded_port", guest: 9091, host: 9091
    cc.vm.provider "virtualbox" do |v|
      v.memory = 4000
      v.cpus = 2
    end
    cc.vm.provision "shell", inline: "> /etc/profile.d/myvars.sh"
    cc.vm.provision "shell", inline: "echo 'export CCD_IMAGE=ci-repo.englab.juniper.net:5010/contrail-command-deployer:#{contrail_version}' >> /etc/profile.d/myvars.sh"
    cc.vm.provision "shell", inline: "echo 'export COMMAND_SERVERS_FILE=/tmp/command_servers.yml' >> /etc/profile.d/myvars.sh"
    cc.vm.provision "shell", inline: "echo 'export INSTANCES_FILE=/tmp/instances.yaml' >> /etc/profile.d/myvars.sh"

    cc.vm.provision "file", source: "#{vagrant_root}/config/command_servers.yml", destination: "/tmp/command_servers.yml"
    cc.vm.provision "file", source: "#{vagrant_root}/config/instances.yaml", destination: "/tmp/instances.yaml"

    cc.vm.provision "shell", path: "#{vagrant_root}/ansible/scripts/docker.sh"
    cc.vm.provision :ansible do |ansible|
      ansible.playbook = "#{vagrant_root}/ansible/setup.yml"
      ansible.extra_vars = {
        set_root_pass: "contrail",
      }
    end
    cc.vm.provision "file", source: "#{vagrant_root}/ansible/scripts/cc.sh", destination: "/tmp/cc.sh"
  end
end
